version: '3.8'

services:
  vault:
    image: vault:1.8.4
    container_name: vault
    tty: true
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault/vault.json:/vault/config/vault.json
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
      - ./vault/logs:/vault/logs
      - ./plugins/quorum-hashicorp-vault-plugin:/vault/plugins/quorum-hashicorp-vault-plugin:ro
    environment:
      ROOT_TOKEN_PATH: /vault/.root
      VAULT_ADDR: http://vault:8200
    entrypoint:
      - sh
      - -c
      - |
        # apk add jq
        # apk add --no-cache curl
        # chmod +x /vault/vault-init.sh
        # ( sleep 10 ; /vault/vault-init.sh ) &
        vault server -config=/vault/config/vault.json
    ports:
      - 8200:8200
    healthcheck:
      test: [ "CMD", "wget", "--spider", "--proxy", "off", "http://localhost:8200/v1/sys/health?standbyok=true" ]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 5s